name: Build Android App with Buildozer

on: push: branches: - main pull_request: branches: - main

jobs: build: runs-on: ubuntu-latest

steps:
- name: Checkout code
  uses: actions/checkout@v4

- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.9'

# Paso crucial: instalar las dependencias de Python de tu proyecto
# Este paso asume que tienes un archivo requirements.txt en la raíz de tu repositorio
- name: Install Python dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

# Se usa caché para que el SDK de Android no se descargue en cada ejecución,
# lo que acelera enormemente el proceso.
- name: Cache Android SDK
  uses: actions/cache@v4
  with:
    path: ~/.buildozer
    key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

- name: Install Buildozer and dependencies
  run: |
    pip install cython buildozer

# El siguiente paso ejecuta la compilación de Android
# Es importante que el archivo buildozer.spec esté en la raíz de tu repositorio
- name: Build Android debug APK
  run: |
    buildozer -v android debug

# Este paso sube el archivo APK generado como un "artefacto" de GitHub Actions.
# Así podrás descargarlo directamente desde la página del flujo de trabajo.
- name: Upload APK as artifact
  uses: actions/upload-artifact@v4
  with:
    name: calculator-app-apk
    path: bin/*.apk
