name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk wget

    - name: Install Android SDK and tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p ~/android-sdk/cmdline-tools
        mv cmdline-tools ~/android-sdk/cmdline-tools/latest
        echo "ANDROID_SDK_ROOT=~/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:~/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

    - name: Accept Android licenses
      run: |
        yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android build-tools and platform
      run: |
        ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34"

    - name: Install Buildcore and dependencies
      run: |
        pip install cython buildozer

    - name: Build RPK
      run: |
        buildozer -v android debug
