name: Build Android App with Buildozer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Update system packages
      # Paso aislado para apt-get update con depuración extendida
      run: |
        echo "Attempting to update system packages..."
        # Captura tanto stdout como stderr
        sudo apt-get update -y 2>&1 | tee apt_update_log.txt
        # Revisa el código de salida y muestra el log si falla
        if [ $? -ne 0 ]; then
          echo "Error: apt-get update failed!"
          cat apt_update_log.txt
          exit 1
        fi
        echo "System packages updated successfully."

    - name: Install system dependencies
      # Paso aislado para apt-get install con depuración extendida
      run: |
        echo "Attempting to install required system dependencies..."
        # Captura tanto stdout como stderr
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 \
          cmake libffi-dev libssl-dev build-essential \
          libltdl-dev 2>&1 | tee apt_install_log.txt
        # Revisa el código de salida y muestra el log si falla
        if [ $? -ne 0 ]; then
          echo "Error: apt-get install failed!"
          cat apt_install_log.txt
          # También podemos intentar mostrar logs de dpkg para más detalles
          echo "Attempting to show dpkg logs for more info:"
          sudo cat /var/log/dpkg.log || echo "dpkg.log not found or inaccessible."
          exit 1
        fi
        echo "System dependencies installed successfully."

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found. Skipping app dependencies installation."
        fi
        
    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-global-${{ runner.os }}-
    - name: Cache Buildozer local directory
      uses: actions/cache@v4
      with:
        path: .buildozer
        key: buildozer-local-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-local-${{ runner.os }}-
    - name: Make bin directory
      run: mkdir -p bin

    - name: Initialize Buildozer (clean build environment)
      run: |
        buildozer android clean || true

    - name: Build Android debug APK
      run: |
        echo "Starting Buildozer build process..."
        yes | buildozer -v android debug
        echo "Buildozer build process completed."
      timeout-minutes: 60

    - name: List generated files
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No 'bin' directory or it's empty."
        echo "Contents of .buildozer/android/platform/build-*/dists/ (where APKs often land):"
        ls -la .buildozer/android/platform/build-*/dists/*/ || echo "APK distribution directory not found or empty."
        echo "Contents of current directory:"
        ls -la
        echo "Searching for APKs in current directory and subdirectories..."
        find . -name "*.apk" || echo "No .apk files found."

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-debug-apk
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/*.apk
        if-no-files-found: warn

    - name: Upload build logs (on failure)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          .buildozer/logs/
          .buildozer/android/platform/build-**/logs/
          buildozer.log
        if-no-files-found: warn
